export const T = {
  TEST: "TEST",
  INIT_PROGRAM: "INIT_PROGRAM",
  SET_DEVICEID: "SET_DEVICEID",
  GET_DEVICEID: "GET_DEVICEID",
  GET_EVENT: "GET_EVENT",
  GET_LOCATION_FROM_IP: "GET_LOCATION_FROM_IP",

  UPDATE_PROCESS_LIST: "UPDATE_PROCESS_LIST",
  UPDATE_PROCESS: "UPDATE_PROCESS",
  CREATE_PROCESS: "CREATE_PROCESS",
  DELETE_PROCESS: "DELETE_PROCESS"
};
